 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/02/Dont-Sit-Under-The-Apple-Tree.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/A-World-Of-Our-Own.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Bad-Moon-Rising.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Bare-Necessities.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Bring-Me-Sunshine.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Brown-Eyed-Girl.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Da-Doo-Ron-Ron.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/11/Daisy-Bell.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/11/Dedicated-Follower-of-Fashion.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/10/8-Days-A-Week-Tab.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/10/Five-Foot-Two_Yes-Sir_Baby-Face-Mashup.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Freight-Train.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Frosty-The-Snowman.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/10/Happy-Birthday.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2017/02/Hello-Mary-Lou.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Ill-Fly-Away.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/I-Wanna-Be-Like-You.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/11/Jingle-Bells.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/02/King-Of-The-Road.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/11/Marys-Boy-Child.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/10/Mellow-Yellow.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Oh-Susanna_Round-The-Mountain_Let-It-Shine.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/10/Please-Dont-Talk-About-Me.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/11/Que-Sera-Sera.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/11/Rock-Around-The-Clock.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Rockin-All-Over-The-World.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/11/Rockin-Around-The-Christmas-Tree.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/11/Rudolph-The-Red-Nosed-Reindeer.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/02/San-Francisco-Bay-Blues.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/04/Save-The-Last-Dance-For-Me.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Side-By-Side_Show-Me-The-Way.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/11/Silver-Bells.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Sloop-John-B.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Stand-By-Me.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/Swinging-On-A-Star.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Then-He-Kissed-Me.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/04/These-Boots-Are-Made-For-Walkin.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Tickle-My-Heart.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2017/02/Top-of-the-World.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2017/02/Urban-Spaceman.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/11/We-Wish-You-A-Merry-Christmas.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/11/White-Christmas.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/11/Winter-Wonderland.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/11/Wonderful-World.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2015/10/The-Yellow-Rose-Of-Texas.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/04/Yellow-Submarine.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/01/You-Are-My-Sunshine.pdf
 wget -P pdf http://www.wymondhamukulelegroup.com/wp-content/uploads/2016/03/Zip-A-Dee-Doo-Dah.pdf
